#!/usr/bin/env bash
# Install nginx web server
sudo apt update
sudo apt -y install nginx
sudo rm /var/www/html/*
sudo touch /var/www/html/index.html
sudo chmod 666 /var/www/html/index.html
sudo echo "Hello World" >> /var/www/html/index.html
sudo service nginx restart
