#!/usr/bin/env bash
# Redirecting to another page
sudo apt update
sudo apt -y install nginx
sudo service nginx start
echo "Hello World" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
