#!/usr/bin/env bash
# Double the number of webservers
sudo apt -y update
sudo apt -y install nginx
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo echo "Hello World" >> /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "\ \t\t add_header X-Served-By ${HOSTNAME};\n" /etc/nginx/sites-available/default
sudo service nginx restart
